In [2]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
a = [1,2,3,4]

In [5]:
type(a)

list

In [6]:
x = np.array(a)

In [7]:
type(x)

numpy.ndarray

In [8]:
x

array([1, 2, 3, 4])

In [9]:
l = [1,2,3,4.5,6]

In [10]:
l = np.array(l)  # upscalling data and of same datatype
l

array([1. , 2. , 3. , 4.5, 6. ])

In [11]:
l[2]

3.0

In [12]:
y = np.array([1,2,3,'a','vv']) # all of them are changed to string
y

array(['1', '2', '3', 'a', 'vv'], dtype='<U21')

In [13]:
k = np.array([1,2,3,'a',{'five':{1:9}}]) # here every things are converted to object
k

array([1, 2, 3, 'a', {'five': {1: 9}}], dtype=object)

In [14]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
a = np.array(arr)

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
arr[2,2]

TypeError: list indices must be integers or slices, not tuple

In [21]:
arr[2][2]

9

In [20]:
a[2,2]

9

In [22]:
a[2][2]

9

In [23]:
### generate values b/w array

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
s = np.arange(30,50)

In [31]:
s

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [32]:
s.shape

(20,)

In [33]:
### can change the shape of array 
## (rows coluns) and rows*cols = s.shape value

s.reshape(10,2)    # 10*2 = 20

array([[30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [34]:
s.reshape(5,4)

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49]])

In [35]:
s.reshape(5,2)

ValueError: cannot reshape array of size 20 into shape (5,2)

In [40]:
# 2d & 3d

s.reshape(2,2,5)

array([[[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [41]:
s     # this remains same 

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [42]:
# so reassign

s = s.reshape(4,5)

In [43]:
s

array([[30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [45]:
s.flatten()     # to linear single dim

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [46]:
## Generate a array with all values as ones 
# (rows,cols)

np.ones((1,2))

array([[1., 1.]])

In [48]:
np.ones((6,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [49]:
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [64]:
# element wise operation

y = np.zeros((5,5))

In [65]:
y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
y = y + 1
y               # updated to each and every value

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
y * 2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [70]:
x = np.ones((3,3))
y = np.zeros((3,3)) + 2
print(x,"\n\n",y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [71]:
z = x+y

In [72]:
z

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [73]:
z = x*y

In [74]:
z

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [97]:
a = np.ones((1,4)) * 3

In [98]:
b = np.ones((1,10)) * 2

In [99]:
print(a ,"\n\n", b)

[[3. 3. 3. 3.]] 

 [[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


In [100]:
z = a * b

ValueError: operands could not be broadcast together with shapes (1,4) (1,10) 

In [101]:
z = [1,2,3,4,45,5,1,32,4,5,4]

In [103]:
z = np.array(z)

In [ ]:
## Means 

In [104]:
z

array([ 1,  2,  3,  4, 45,  5,  1, 32,  4,  5,  4])

In [105]:
z.mean()

9.636363636363637

In [106]:
z.sum()

106

In [107]:
z.var()

194.59504132231405

In [108]:
z.std()

13.949732661320576

In [112]:
z = np.array([[1,2,3,4,5],[6,7,7,8,9]])

In [114]:
# mean of axis = 0 means column elements 
z.mean(axis = 0)

array([3.5, 4.5, 5. , 6. , 7. ])

In [115]:
# mean of axis = 1 means row wise elements 
z.mean(axis = 1)

array([3. , 7.4])

In [109]:
np.mean([1,2,3,4])

2.5

In [116]:
## pi value

np.pi

3.141592653589793

In [117]:
a = [1,2,3,4,5,6]

np.max(a)

6

In [118]:
np.min(a)

1

In [119]:
np.abs(-4)

4

In [120]:
np.log(50)  # base e

3.912023005428146

In [121]:
np.log10(340)

2.5314789170422554

In [122]:
np.log2(4)

2.0

In [124]:
np.sin(60)   # here 60 is radian

-0.3048106211022167

In [127]:
np.sin(60 * (1/np.pi))

0.2464710238112635

In [ ]:
# there ARE many funtions for this

np.random.

In [128]:
np.random.rand(10,2)

array([[0.17948736, 0.05867164],
       [0.51652451, 0.94520337],
       [0.05004467, 0.51340853],
       [0.43335126, 0.53345249],
       [0.42786933, 0.43199168],
       [0.10036607, 0.1803781 ],
       [0.32586758, 0.8974097 ],
       [0.81332176, 0.37113722],
       [0.15741653, 0.86856036],
       [0.15413729, 0.45629928]])

In [130]:
np.random.randint(10)

9

In [131]:
np.random.randint(10,40)

19

In [132]:
np.random.randint(10,40,4)

array([27, 33, 22, 13])

In [3]:
np.linspace(0,10,11)          # returns values that are equidistance in every consequtive nos 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [4]:
np.linspace(1,15,11)   

array([ 1. ,  2.4,  3.8,  5.2,  6.6,  8. ,  9.4, 10.8, 12.2, 13.6, 15. ])

## Normal and Gaussian distribution 

In [4]:
# mean , variance , nos of data points 

np.random.normal(0,4,3)

array([-4.48475187,  6.50491266, -1.28412452])

### sampling and concept of seeding